'use client';
import {useEffect,useState,useRef} from 'react';
import ClientSpend from './client-spend';
import AccountSpend from './account-spend';
import ThemeToggle from './theme-toggle';
import {readApiResponse} from '@/lib/api-response';
import MetaConnections,{type MetaConnection} from './meta-connections';
import {RefreshCw,Wallet,Link2,Search,Copy,Check, Pencil,Users,ArrowDownRight,ShieldCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Toaster,toast} from 'sonner';
type Account={totalSpent?:{amount:number,since:string|null,until:string|null,checkedAt:string}|null,totalSpentError?:string,accountStatus?:number|null,id:string,name:string,currency:string,balance:number|null,budget:number|null,active:number,budgetNote:string,updatedAt:string,source:string};
type Mapping={name:string,tracked:boolean,updatedDay:string};
const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const money=(n:number|null,c='INR')=>n===null?'Unavailable':new Intl.NumberFormat('en-IN',{style:'currency',currency:c,maximumFractionDigits:2}).format(n);
async function api(body?:any){const r=await fetch('/api/dashboard',{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});return readApiResponse(r);}
export default function Dashboard(){
 const [accounts,setAccounts]=useState<Account[]>([]),[mappings,setMappings]=useState<Record<string,Mapping>>({}),[connected,setConnected]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[connect,setConnect]=useState(false),[saving,setSaving]=useState(false),[edit,setEdit]=useState<Account|null>(null),[client,setClient]=useState(''),[tracked,setTracked]=useState(true),[failed,setFailed]=useState<Record<string,string>>({});
 const [readOnly,setReadOnly]=useState(true),[teamHelp,setTeamHelp]=useState(false);
 const refreshLock=useRef(false),nextRefresh=useRef(0),refreshLatest=useRef<()=>Promise<void>>(async()=>{});
 const [refreshEpoch,setRefreshEpoch]=useState(0),[lastChecked,setLastChecked]=useState(''),[refreshSummary,setRefreshSummary]=useState('Waiting for automatic update');
 const [connections,setConnections]=useState<MetaConnection[]>([]);
 async function load(){try{setError('');const j=await api();setAccounts(j.accounts);setMappings(j.mappings);setConnected(j.connected);setReadOnly(j.readOnly===true);setConnections(j.connections||[]);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const ctrl=new AbortController();Promise.resolve(ctx.registerTool({name:'read_fund_accounts',description:'Read the accounts and saved client mappings currently shown in the fund dashboard.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:any)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('No arguments expected');return accounts.map(a=>({...a,client:mappings[a.id]?.name||'',tracked:!!mappings[a.id]?.tracked}));}},{signal:ctrl.signal})).catch(()=>{});return()=>ctrl.abort();},[accounts,mappings]);
 const [clock,setClock]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),60000);return()=>clearInterval(timer);},[]);
 const stale=(a:Account)=>a.source!=='live'||!a.updatedAt||clock-Date.parse(a.updatedAt)>15*60*1000||!!failed[a.id];
 const inDisabled=(a:Account)=>a.accountStatus===2||a.balance===null;
 const low=(a:Account)=>!stale(a)&&a.accountStatus!==2&&a.balance!==null&&a.budget!==null&&a.budget>0&&a.balance<a.budget;
 const status=(a:Account)=>inDisabled(a)?'Disabled':stale(a)?'Refresh required':a.balance===null?'Balance unavailable':a.budget===null?'Review budget':a.budget===0?'No active budget':low(a)?'Low funds':'Covered';
 async function refresh(){if(refreshLock.current)return;setError('');if(!connected){if(readOnly)toast.error('Ask the dashboard owner to connect Meta.');else setConnect(true);return;}refreshLock.current=true;setBusy(true);setRefreshSummary('Updating accounts…');setFailed({});let success=0;const errors:Record<string,string>={};try{setProgress('Finding accounts…');const j=await api({action:'list'});setConnections(j.connections||[]);const connectionErrors=(j.connections||[]).filter((c:MetaConnection)=>c.error).map((c:MetaConnection)=>`${c.label}: ${c.error}`);let current:Account[]=j.accounts.map((a:any)=>accounts.find(x=>x.id===a.id)||{...a,balance:null,budget:null,active:0,source:'pending',updatedAt:'',budgetNote:''});setAccounts(current);for(let i=0;i<j.accounts.length;i++){const a=j.accounts[i];setProgress(`${i+1} / ${j.accounts.length} · ${a.name}`);try{const r=await api({action:'refresh',id:a.id});current=current.map(x=>x.id===a.id?r.account:x);setAccounts([...current]);setClock(Date.now());success++;}catch(e){errors[a.id]=(e as Error).message;setFailed({...errors});}}setLastChecked(new Date().toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}));setRefreshSummary(success===j.accounts.length&&!connectionErrors.length?'Data updated':`${success} of ${j.accounts.length} accounts updated · some updates failed`);if(Object.keys(errors).length||connectionErrors.length)setError([...connectionErrors,...Object.values(errors)].join(' · '));}catch(e){const message=(e as Error).message;setRefreshSummary('Update failed · will retry automatically');setError(message);setFailed(Object.fromEntries(accounts.map(a=>[a.id,message])));if(/token expired|invalid/i.test(message))setConnected(false);}finally{refreshLock.current=false;nextRefresh.current=Date.now()+5*60*1000;setRefreshEpoch(x=>x+1);setBusy(false);setProgress('');}}
 refreshLatest.current=refresh;
 useEffect(()=>{if(loading||!connected)return;const tick=()=>{if(document.visibilityState==='visible'&&navigator.onLine&&!refreshLock.current&&Date.now()>=nextRefresh.current)void refreshLatest.current();};tick();const timer=setInterval(tick,10000);document.addEventListener('visibilitychange',tick);window.addEventListener('online',tick);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',tick);window.removeEventListener('online',tick);};},[loading,connected]);
 async function saveMapping(a:Account,m:Mapping){await api({action:'client',id:a.id,...m});setMappings(x=>({...x,[a.id]:m}));}
 async function copy(a:Account){if(stale(a)||a.accountStatus===2||a.balance===null||a.budget===null)return;const msg=a.balance<=0?'Sir, your account funds are exhausted. Please add funds to continue running your ads.':low(a)?`Sir, aapke account mein abhi ${money(a.balance,a.currency)} fund available hai—please aur fund add karwa dijiye taaki ads smoothly run hote rahein.`:'Aaj ke liye balance sufficient hai.';try{await navigator.clipboard.writeText(msg);toast.success('Reminder copied. Paste it into your client chat.');}catch{toast.error('Clipboard unavailable. Please allow clipboard access.');}}
 const stamp=(a:Account)=>a.updatedAt?new Date(a.updatedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'Not checked';
 const shown=accounts.filter(a=>(a.name+' '+a.id+' '+(mappings[a.id]?.name||'')).toLowerCase().includes(query.toLowerCase())&&(filter==='disabled'?inDisabled(a):!inDisabled(a)&&(filter==='all'||filter==='low'&&low(a))));
 const known=accounts.filter(a=>!inDisabled(a)&&!stale(a)&&a.currency==='INR'),total=known.reduce((s,a)=>s+(a.balance||0),0),imported=accounts.some(a=>a.source==='import');
 return <div className="desk"><Toaster richColors/><header className="topbar"><div className="brand"><span className="brand-icon"><Wallet size={22}/></span><div>Fund Desk<small>Client accounts</small></div></div><div className="top-actions"><ThemeToggle/><span className="private"><ShieldCheck size={16}/>{readOnly?'Team view':'Private workspace'}</span>{!readOnly&&<Button variant="outline" onClick={()=>setTeamHelp(true)}><Users size={16}/>Team access</Button>}{!readOnly&&<Button variant="outline" disabled={busy} onClick={()=>setConnect(true)}><Link2 size={16}/>{connected?`Facebook IDs (${connections.length})`:'Connect Meta'}</Button>}</div></header><main>
 <div className="heading"><div><p className="eyebrow">YOUR WORKSPACE</p><h1>Overview</h1><p className="muted">Your client balances, daily budgets and spend.</p></div><Button className="refresh" disabled={busy||loading} onClick={()=>void refresh()}><RefreshCw size={17} className={busy?'spin':''}/>{busy?'Refreshing…':'Refresh all accounts'}</Button></div>
 <div className="notice sync-status" role="status"><RefreshCw size={17} className={busy?'spin':''}/><div><strong>{connected?refreshSummary:'Connect Meta to enable automatic updates'}</strong><p>Every 5 minutes while open.{lastChecked&&` Last checked: ${lastChecked} IST.`}</p></div></div>
 {error&&<div className="notice danger" role="alert">{error}<Button variant="outline" onClick={()=>!readOnly&&/token expired|invalid/i.test(error)?setConnect(true):load()}>{!readOnly&&/token expired|invalid/i.test(error)?'Reconnect Meta':'Retry loading'}</Button></div>}
 {!connected&&!readOnly&&<div className="notice"><Link2 size={19}/><div><strong>Connect Meta for fresh balances and budgets</strong><p>Your imported accounts are ready below. Add a new access token once, balances will update automatically.</p></div><Button variant="outline" onClick={()=>setConnect(true)}>Set up connection</Button></div>}
 {imported&&<p className="snapshot">Imported snapshot · 28 Sep 2026. These values are not live until refreshed.</p>}
 {accounts.some(a=>!inDisabled(a)&&stale(a))&&<div className="notice">Some balances are old or could not refresh. They are shown as last known values, excluded from the fresh total, and cannot be copied into client messages. Connect Meta and refresh to check current funds.</div>}
 {busy&&<div className="notice" role="status">{progress}</div>}
 <section className="stats"><article><Wallet className="stat-icon" size={22}/><span>Fresh available funds · INR</span><strong>{known.length?money(total):'—'}</strong><small>{known.length} accounts checked in the last 15 minutes</small></article><article><ArrowDownRight className="stat-icon" size={22}/><span>Accounts to check</span><strong className="red">{accounts.filter(low).length.toString().padStart(2,'0')}<ArrowDownRight size={25}/></strong><small>Below one day’s set budget</small></article><article><Check className="stat-icon" size={22}/><span>Daily client updates</span><strong>{accounts.filter(a=>!inDisabled(a)&&mappings[a.id]?.tracked).length.toString().padStart(2,'0')}</strong><small>{accounts.filter(a=>!inDisabled(a)&&mappings[a.id]?.tracked&&mappings[a.id]?.updatedDay===day()).length} marked updated today</small></article><article><ShieldCheck className="stat-icon" size={22}/><span>Disabled section</span><strong>{accounts.filter(inDisabled).length.toString().padStart(2,'0')}</strong><small>Disabled and missing-balance accounts</small></article></section>
 <details className="client-spend-disclosure"><summary>Client spend <span>View combined spend by client</span></summary><ClientSpend refreshEpoch={refreshEpoch} parentBusy={busy||loading} accounts={accounts} mappings={mappings} connected={connected} onConnect={()=>readOnly?toast.error('Ask the dashboard owner to connect Meta.'):setConnect(true)}/></details>
 <section className="accounts"><div className="table-heading"><div><h2>Ad accounts <span>{shown.length}</span></h2><p>{readOnly?'All shared ad accounts and client balances.':'Use “Link client” to save the client name for an account.'}</p></div><div className="search"><Search size={17}/><Input aria-label="Search clients or accounts" placeholder="Search client or account…" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><Tabs value={filter} onValueChange={setFilter}><TabsList className="filters"><TabsTrigger value="all">All accounts</TabsTrigger><TabsTrigger value="low">Low funds</TabsTrigger><TabsTrigger value="disabled">Disabled</TabsTrigger></TabsList></Tabs>
 <Table><TableHeader><TableRow><TableHead>CLIENT / AD ACCOUNT</TableHead><TableHead className="number">DAILY BUDGET</TableHead><TableHead className="number">AVAILABLE FUND</TableHead><TableHead className="number">TOTAL SPENT</TableHead><TableHead>STATUS</TableHead><TableHead>CLIENT UPDATE</TableHead></TableRow></TableHeader><TableBody>{shown.map(a=><TableRow key={a.id} className={low(a)?'low-row':''}><TableCell><button className="client-link" disabled={readOnly} onClick={()=>{setEdit(a);setClient(mappings[a.id]?.name||'');setTracked(mappings[a.id]?.tracked??true);}}>{mappings[a.id]?.name||(readOnly?'Unlinked client':'Link client')}{!readOnly&&<Pencil size={13}/>}</button><div className="account-name">{a.name}</div><div className="meta">…{a.id.slice(-6)} · {a.source==='import'?'Imported':stamp(a)}</div></TableCell><TableCell className="number budget">{a.accountStatus===2?'—':money(a.budget,a.currency)}<small>{a.budgetNote||'per day'}</small></TableCell><TableCell className={'number balance '+(low(a)?'red':'')}>{a.balance===null?'—':money(a.balance,a.currency)}{!inDisabled(a)&&stale(a)&&<small className="stale-label">Last known · refresh required</small>}</TableCell><TableCell className="number balance total-spent"><AccountSpend account={a} stale={stale(a)}/></TableCell><TableCell><span className={'badge '+(inDisabled(a)?'bad':stale(a)?'neutral':low(a)?'bad':a.balance===null||a.budget===null?'neutral':a.budget===0?'neutral':'good')}>{status(a)}</span>{inDisabled(a)&&a.accountStatus!==2&&<small className="error-detail">Grouped: balance missing</small>}{failed[a.id]&&<small className="error-detail">{failed[a.id]}</small>}</TableCell><TableCell><div className="row-actions"><Button size="sm" variant="outline" disabled={stale(a)||a.accountStatus===2||a.balance===null||a.budget===null||!!failed[a.id]} onClick={()=>copy(a)}><Copy size={14}/>Copy</Button><Button size="sm" variant="ghost" disabled={readOnly||stale(a)||inDisabled(a)||!mappings[a.id]?.name} onClick={async()=>{try{await saveMapping(a,{...mappings[a.id],updatedDay:mappings[a.id]?.updatedDay===day()?'':day()});}catch{toast.error('Could not save update.');}}}>{mappings[a.id]?.updatedDay===day()?<><Check size={15}/>Updated</>:'Mark updated'}</Button></div></TableCell></TableRow>)}</TableBody></Table>
 {loading&&<div className="empty">Loading your accounts…</div>}{!loading&&!shown.length&&<div className="empty"><Users/><h3>No accounts here yet</h3><p>Try another search or connect Meta and refresh.</p></div>}
 </section><footer>Use Choose dates under Total spent to load one account’s spend for a selected period. Maximum history uses Meta’s available reporting history; older history may be excluded. Dates under each amount show its period. It is ad spend, not funds added. Budgets are configured daily amounts, not actual spend. Active status does not confirm ad delivery. Funds are compared with one day’s budget, excluding any additional tax allowance. Times shown in IST.</footer>
 </main>
 <Dialog open={teamHelp} onOpenChange={setTeamHelp}><DialogContent><DialogTitle>Share with your team</DialogTitle><DialogDescription>Invited team members can see all client accounts, balances, budgets and spend in this dashboard.</DialogDescription><p>To add or remove a team member, send their sign-in email to Codex in the conversation where you created this dashboard. Access is restricted to approved people.</p><p className="muted">Members can refresh data and copy reminders. Only you can change client names and Facebook connections.</p><Button onClick={async()=>{try{await navigator.clipboard.writeText(window.location.origin);toast.success('Dashboard link copied. The member must be granted access before opening it.');}catch{toast.error('Could not copy the link.');}}}>Copy dashboard link</Button></DialogContent></Dialog>
 <Dialog open={connect} onOpenChange={setConnect}><DialogContent className="connections-dialog"><DialogTitle>Facebook ID connections</DialogTitle><DialogDescription>Manage the Facebook IDs used to check your clients’ accounts.</DialogDescription><MetaConnections connections={connections} onChange={load}/></DialogContent></Dialog>
 <Dialog open={!!edit} onOpenChange={v=>{if(!v)setEdit(null);}}><DialogContent><DialogTitle>Link client</DialogTitle><DialogDescription>{edit?.name} · {edit?.id}</DialogDescription><label htmlFor="client">Client name</label><Input id="client" list="saved-clients" placeholder="e.g. Neha" maxLength={100} value={client} onChange={e=>setClient(e.target.value)}/><datalist id="saved-clients">{Array.from(new Set(Object.values(mappings).map(m=>m.name).filter(Boolean))).map(name=><option key={name} value={name}/>)}</datalist><p className="muted text-sm">Use the same client name on all of their ad accounts to combine their spend.</p><label className="checkline"><Checkbox checked={tracked} onCheckedChange={v=>setTracked(v===true)}/>Include in daily client updates</label><Button disabled={saving||!client.trim()} onClick={async()=>{if(!edit)return;setSaving(true);try{await saveMapping(edit,{name:client,tracked,updatedDay:mappings[edit.id]?.updatedDay||''});setEdit(null);toast.success('Client linked');}catch(e){toast.error((e as Error).message);}finally{setSaving(false);}}}>Save client</Button></DialogContent></Dialog>
 </div>;
}
