'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {toast} from 'sonner';
export type MetaConnection={id:string,label:string,error:string|null,checkedAt:string|null,accountCount:number|null};
export default function MetaConnections({connections,onChange}:{connections:MetaConnection[],onChange:()=>Promise<void>}){
 const [editing,setEditing]=useState<string|null>(null),[label,setLabel]=useState(''),[token,setToken]=useState(''),[busy,setBusy]=useState(false),[remove,setRemove]=useState('');
 async function request(body:any){const r=await fetch('/api/dashboard',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j:any=await r.json();if(!r.ok)throw Error(j.error||'Please retry.');}
 return <div className="connection-manager">
 <p className="muted">Add each Facebook ID with its own access token. Shared ad accounts appear once.</p>
 {connections.map(c=><div className="connection-card" key={c.id}><strong>{c.label}</strong><p className="muted">{c.accountCount===null?'Refresh to find accounts':`${c.accountCount} accessible ad accounts`}</p>{c.error&&<p role="alert" className="error-detail">{c.error}</p>}<div className="row-actions"><Button variant="outline" disabled={busy} onClick={()=>{setEditing(c.id);setLabel(c.label);setToken('');setRemove('');}}>Update token</Button><Button variant="ghost" disabled={busy} onClick={()=>setRemove(c.id)}>Remove</Button></div>{remove===c.id&&<div><p>Remove this connection? Accounts accessible through another ID will remain. Saved client names are kept.</p><Button variant="outline" disabled={busy} onClick={async()=>{setBusy(true);try{await request({action:'disconnect',connectionId:c.id});await onChange();setRemove('');if(editing===c.id)setEditing(null);toast.success('Connection removed');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}}>Confirm remove</Button><Button variant="ghost" onClick={()=>setRemove('')}>Cancel</Button></div>}</div>)}
 {editing===null?<Button disabled={busy} onClick={()=>{setEditing('');setLabel('');setToken('');}}>+ Add Facebook ID</Button>:<form className="connection-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await request({action:'connect',connectionId:editing||undefined,label,token});setToken('');setEditing(null);await onChange();toast.success('Connection saved. Click Refresh all accounts.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}}><strong>{editing?'Update connection':'Add Facebook ID'}</strong><label htmlFor="connection-name">Connection name</label><Input id="connection-name" maxLength={100} placeholder="e.g. Aayush / Office ID 2" value={label} onChange={e=>setLabel(e.target.value)}/><label htmlFor="connection-token">Access token</label><Input id="connection-token" type="password" autoComplete="off" placeholder="Paste this Facebook ID’s token" value={token} onChange={e=>setToken(e.target.value)}/><p className="muted">Use a user token with ads_read permission. Tokens stay on the server and are never displayed back.</p><Button type="submit" disabled={busy||!token.trim()}>{busy?'Checking accounts…':'Save connection'}</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>{setEditing(null);setToken('');}}>Cancel</Button></form>}
 </div>;
}
